# Generated by Django 5.2.3 on 2025-07-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public - Everyone"),
                    ("community", "Community Only"),
                    ("verified_only", "Verified Members Only"),
                ],
                default="public",
                help_text="Who can see this listing",
                max_length=20,
            ),
        ),
    ]
