# Generated by Django 5.2.3 on 2025-07-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_listing_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public - Everyone"),
                    ("community", "All Community Members"),
                    ("same_origin", "Same Country of Origin"),
                    ("verified_only", "Verified Members Only"),
                ],
                default="public",
                help_text="Who can see this listing",
                max_length=20,
            ),
        ),
    ]
