# Generated by Django 5.2.3 on 2025-07-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_alter_listing_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("community", "Only Your Community People"),
                    ("same_origin", "Only Your Origin Country"),
                    ("verified_only", "Verified Users Only"),
                ],
                default="public",
                help_text="Who can see this listing",
                max_length=20,
            ),
        ),
    ]
