# Generated by Django 5.2.3 on 2025-07-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_alter_listing_visibility"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["-priority_score", "name"],
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="priority_score",
            field=models.IntegerField(
                default=0,
                help_text="Higher numbers show first. Use 100+ for top priority categories.",
            ),
        ),
    ]
